-- ===============================
-- V1: INITIAL SCHEMA
-- ===============================

-- Profiles table (OneToOne with users)
CREATE TABLE profiles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(100),
                          last_name VARCHAR(100)
);

-- Users table
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       profile_id BIGINT UNIQUE
);

-- OneToOne: users.profile_id -> profiles.id
ALTER TABLE users
    ADD CONSTRAINT fk_users_profiles
        FOREIGN KEY (profile_id) REFERENCES profiles(id);

-- Posts table (OneToMany: user -> posts)
CREATE TABLE posts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       title VARCHAR(255),
                       content TEXT
);

-- OneToMany: posts.user_id -> users.id
ALTER TABLE posts
    ADD CONSTRAINT fk_posts_users
        FOREIGN KEY (user_id) REFERENCES users(id);

-- Roles table (used for ManyToMany)
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL UNIQUE
);

-- ManyToMany: users <-> roles through user_roles
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            FOREIGN KEY (user_id) REFERENCES users(id),
                            FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Indexes
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_users_username ON users(username);